name: 代码重构助手
version: "1.0.0"
description: 分析代码质量问题，提供重构建议并自动执行安全重构
created_at: "2026-02-11T15:40:00"
source: "改编自Claude Code最佳实践"
category: "code-quality"
tags: ["refactoring", "code-quality", "automation", "cleanup"]
triggers:
  - "重构代码"
  - "代码重构"
  - "优化代码"
  - "code refactor"
steps:
  - id: 1
    name: 分析代码质量
    action: run_command
    params:
      command: "echo 分析代码复杂度、重复代码..."
      save_as: quality_analysis
      timeout: 15

  - id: 2
    name: 识别重构机会
    action: run_command
    params:
      command: "echo 识别需要重构的代码块..."
      save_as: refactor_targets
      timeout: 10

  - id: 3
    name: 生成重构计划
    action: run_command
    params:
      command: "echo 制定重构步骤和优先级..."
      save_as: refactor_plan
      timeout: 10

  - id: 4
    name: 执行安全重构
    action: run_command
    params:
      command: "echo 执行安全的重构操作..."
      save_as: refactor_results
      timeout: 20

  - id: 5
    name: 生成重构报告
    action: generate_document
    params:
      template: "code-refactor.md"
      variables:
        analysis: "{{quality_analysis}}"
        targets: "{{refactor_targets}}"
        plan: "{{refactor_plan}}"
        results: "{{refactor_results}}"
        date: "{{current_date}}"
      output: "docs/code-refactor-{{current_date}}.md"
      save_as: report_path

  - id: 6
    name: 完成通知
    action: notify
    params:
      message: |
        代码重构完成！
        质量问题: {{quality_analysis}}
        重构目标: {{refactor_targets}}
        重构结果: {{refactor_results}}
        报告路径: {{report_path}}