name: 依赖检查
description: 检查项目依赖更新和安全漏洞
version: "1.0.0"
created_at: "2026-02-11T12:00:00"
source: "改编自开源安全最佳实践"
triggers:
  - "检查依赖"
  - "dependency check"
  - "更新依赖"
  - "安全扫描"
steps:
  - id: 1
    name: 检查Python依赖
    action: run_command
    params:
      command: "if exist requirements.txt (echo Python依赖文件存在) else (echo 未找到requirements.txt)"
      save_as: python_deps
      timeout: 5

  - id: 2
    name: 检查Node依赖
    action: run_command
    params:
      command: "if exist package.json (echo Node.js项目检测到) else (echo 未找到package.json)"
      save_as: node_deps
      timeout: 5

  - id: 3
    name: 生成依赖报告
    action: generate_document
    params:
      template: "dependency-report.md"
      variables:
        date: "{{current_date}}"
        python_status: "{{python_deps}}"
        node_status: "{{node_deps}}"
      output: "docs/dependency-check-{{current_date}}.md"
      save_as: report_path

  - id: 4
    name: 完成通知
    action: notify
    params:
      message: |
        依赖检查完成！
        Python: {{python_deps}}
        Node.js: {{node_deps}}
        报告: {{report_path}}