name: 日志异常检测
version: "1.0.0"
description: 实时监控日志文件，自动检测异常模式并告警
created_at: "2026-02-11T15:30:00"
source: "改编自ELK Stack日志分析工作流"
category: "monitoring"
tags: ["logging", "anomaly", "monitoring", "alert", "devops"]
triggers:
  - "检测日志异常"
  - "日志分析"
  - "异常告警"
  - "log anomaly"
steps:
  - id: 1
    name: 收集日志文件
    action: run_command
    params:
      command: "echo 扫描日志文件..."
      save_as: log_files
      timeout: 10

  - id: 2
    name: 解析日志格式
    action: run_command
    params:
      command: "echo 解析日志格式和时间戳..."
      save_as: parsed_logs
      timeout: 15

  - id: 3
    name: 异常模式检测
    action: run_command
    params:
      command: "echo 检测ERROR、WARNING、异常堆栈..."
      save_as: anomalies
      timeout: 20

  - id: 4
    name: 生成告警
    action: run_command
    params:
      command: "echo 生成告警通知..."
      save_as: alerts
      timeout: 5

  - id: 5
    name: 生成检测报告
    action: generate_document
    params:
      template: "log-anomaly-report.md"
      variables:
        files: "{{log_files}}"
        parsed: "{{parsed_logs}}"
        anomalies: "{{anomalies}}"
        alerts: "{{alerts}}"
        date: "{{current_date}}"
      output: "docs/log-anomaly-{{current_date}}.md"
      save_as: report_path

  - id: 6
    name: 完成通知
    action: notify
    params:
      message: |
        日志异常检测完成！
        日志文件: {{log_files}}
        检测到的异常: {{anomalies}}
        告警: {{alerts}}
        报告: {{report_path}}