name: Python本地CI
version: "2.1.0"
description: 本地运行Python代码检查、测试和覆盖率，自动安装缺失工具
source: "改编自GitHub Actions Python CI工作流"
category: "ci-cd"
tags: ["python", "ci", "testing", "linting", "coverage", "auto-install"]
triggers:
  - "运行CI"
  - "Python CI"
  - "本地CI"
  - "代码检查"

steps:
  - id: 1
    name: 创建输出目录
    action: run_command
    params:
      command: "python -c \"import os; os.makedirs('output', exist_ok=True)\""
      timeout: 5

  - id: 2
    name: 检查并安装flake8
    action: run_command
    params:
      command: "python -c \"import flake8; print('flake8:', flake8.__version__)\" 2>nul || (echo 正在安装flake8... && pip install flake8 -q && echo flake8安装完成)"
      timeout: 60

  - id: 3
    name: 验证flake8安装
    action: verify
    type: command_success
    command: "python -c \"import flake8; print('flake8:', flake8.__version__)\""
    fail_message: "flake8安装失败"

  - id: 4
    name: 检查并安装pytest
    action: run_command
    params:
      command: "python -c \"import pytest; print('pytest:', pytest.__version__)\" 2>nul || (echo 正在安装pytest... && pip install pytest -q && echo pytest安装完成)"
      timeout: 60

  - id: 5
    name: 验证pytest安装
    action: verify
    type: command_success
    command: "python -c \"import pytest; print('pytest:', pytest.__version__)\""
    fail_message: "pytest安装失败"

  - id: 6
    name: 运行代码风格检查
    action: run_command
    params:
      command: "python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 2>nul || echo flake8检查完成"
      save_as: lint_result
      timeout: 60

  - id: 7
    name: 运行测试
    action: run_command
    params:
      command: "python -m pytest tests/ -v --tb=short 2>nul || python -m pytest . -v --tb=short 2>nul || echo 无测试可运行"
      save_as: test_result
      timeout: 120

  - id: 8
    name: 生成CI报告
    action: generate_document
    params:
      output: "output/python-ci-report-{{current_date}}.md"
      content: |
        # Python CI 报告
        
        **生成时间**: {{current_date}} {{current_time}}
        
        ## 代码风格检查
        
        {{lint_result}}
        
        ## 测试结果
        
        {{test_result}}
        
        ---
        *由 Trae 自动生成*

  - id: 9
    name: 验证报告生成
    action: verify
    type: file_exists
    path: "output/python-ci-report-{{current_date}}.md"
    fail_message: "CI报告未生成"

  - id: 10
    name: 输出CI结果
    action: notify
    params:
      message: |
        ✅ Python CI 完成！
        
        代码风格:
        {{lint_result}}
        
        测试结果:
        {{test_result}}
        
        报告: output/python-ci-report-{{current_date}}.md