name: 简历自动筛选
version: "1.0.0"
description: 自动解析简历，提取关键信息，生成筛选建议
created_at: "2026-02-11T15:20:00"
source: "改编自HR自动化工作流"
category: "automation"
tags: ["hr", "recruitment", "resume", "screening", "automation"]
triggers:
  - "筛选简历"
  - "简历处理"
  - "resume screening"
  - "招聘"
steps:
  - id: 1
    name: 获取简历文件
    action: run_command
    params:
      command: "echo 获取待筛选的简历文件..."
      save_as: resume_files
      timeout: 5

  - id: 2
    name: 解析简历内容
    action: run_command
    params:
      command: "echo 解析PDF/Word格式简历..."
      save_as: parsed_resumes
      timeout: 15

  - id: 3
    name: 提取关键信息
    action: run_command
    params:
      command: "echo 提取技能、经验、学历等关键信息..."
      save_as: key_info
      timeout: 10

  - id: 4
    name: 匹配职位要求
    action: run_command
    params:
      command: "echo 与职位要求进行匹配度分析..."
      save_as: match_results
      timeout: 10

  - id: 5
    name: 生成筛选报告
    action: generate_document
    params:
      template: "resume-screening-report.md"
      variables:
        files: "{{resume_files}}"
        parsed: "{{parsed_resumes}}"
        info: "{{key_info}}"
        matches: "{{match_results}}"
        date: "{{current_date}}"
      output: "docs/resume-screening-{{current_date}}.md"
      save_as: report_path

  - id: 6
    name: 完成通知
    action: notify
    params:
      message: |
        简历筛选完成！
        处理简历: {{resume_files}}
        匹配结果: {{match_results}}
        筛选报告: {{report_path}}