name: 销售线索培育
version: "1.0.0"
description: 自动化销售线索评分、跟进提醒和个性化内容推荐
created_at: "2026-02-11T14:55:00"
source: "改编自HubSpot销售自动化模板"
category: "automation"
tags: ["sales", "leads", "crm", "automation", "marketing"]
triggers:
  - "培育线索"
  - "销售线索"
  - "lead nurturing"
  - "CRM"
steps:
  - id: 1
    name: 获取线索数据
    action: run_command
    params:
      command: "echo 从CRM获取销售线索数据..."
      save_as: lead_data
      timeout: 10

  - id: 2
    name: 线索评分
    action: run_command
    params:
      command: "echo 计算线索质量和购买意向评分..."
      save_as: lead_scores
      timeout: 10

  - id: 3
    name: 分配跟进任务
    action: run_command
    params:
      command: "echo 根据评分分配销售代表和跟进优先级..."
      save_as: followup_tasks
      timeout: 5

  - id: 4
    name: 生成个性化内容
    action: run_command
    params:
      command: "echo 生成个性化跟进邮件和推荐内容..."
      save_as: personalized_content
      timeout: 15

  - id: 5
    name: 生成培育报告
    action: generate_document
    params:
      template: "sales-lead-report.md"
      variables:
        leads: "{{lead_data}}"
        scores: "{{lead_scores}}"
        tasks: "{{followup_tasks}}"
        content: "{{personalized_content}}"
        date: "{{current_date}}"
      output: "docs/sales-lead-nurturing-{{current_date}}.md"
      save_as: report_path

  - id: 6
    name: 完成通知
    action: notify
    params:
      message: |
        销售线索培育完成！
        线索数据: {{lead_data}}
        评分结果: {{lead_scores}}
        跟进任务: {{followup_tasks}}
        报告: {{report_path}}