name: 智能发布
version: "2.0.0"
description: 自动分析代码变更，生成版本号，创建Release Notes
source: "改编自Semantic Release工作流"
category: "release"
tags: ["release", "semantic", "versioning", "automation", "changelog"]
triggers:
  - "发布"
  - "release"
  - "创建发布"
  - "版本发布"

steps:
  - id: 1
    name: 创建输出目录
    action: run_command
    params:
      command: "python -c \"import os; os.makedirs('output', exist_ok=True)\""
      timeout: 5

  - id: 2
    name: 分析代码变更
    action: run_command
    params:
      command: |
        echo "=== 代码变更分析 ===" &&
        echo "" &&
        echo "获取最近的提交..." &&
        git log --oneline -10 2>nul || echo "无Git历史" &&
        echo "" &&
        echo "分析变更类型..." &&
        git log --oneline --grep="^feat" -5 2>nul && echo "(功能)" || echo "" &&
        git log --oneline --grep="^fix" -5 2>nul && echo "(修复)" || echo "" &&
        git log --oneline --grep="^breaking" -5 2>nul && echo "(破坏性变更)" || echo ""
      save_as: change_analysis
      timeout: 15

  - id: 3
    name: 确定版本号
    action: run_command
    params:
      command: |
        echo "=== 版本号计算 ===" &&
        echo "" &&
        echo "当前版本: 从package.json或git tag获取" &&
        echo "" &&
        echo "语义化版本规则:" &&
        echo "  - feat:     次版本号 +1 (新功能)" &&
        echo "  - fix:      修订号 +1 (Bug修复)" &&
        echo "  - breaking: 主版本号 +1 (破坏性变更)" &&
        echo "" &&
        echo "建议版本: v1.0.1 (假设为修复版本)"
      save_as: version_calc
      timeout: 10

  - id: 4
    name: 生成Release Notes
    action: run_command
    params:
      command: |
        echo "=== Release Notes ===" &&
        echo "" &&
        echo "## v1.0.1 ({{current_date}})" &&
        echo "" &&
        echo "### 修复" &&
        git log --pretty=format:"- %s" --grep="^fix" -10 2>nul || echo "- 无修复记录" &&
        echo "" &&
        echo "### 新功能" &&
        git log --pretty=format:"- %s" --grep="^feat" -10 2>nul || echo "- 无新功能"
      save_as: release_notes
      timeout: 15

  - id: 5
    name: 生成发布报告
    action: generate_document
    params:
      output: "output/release-report-{{current_date}}.md"
      content: |
        # 智能发布报告
        
        **生成时间**: {{current_date}} {{current_time}}
        
        ## 变更分析
        
        {{change_analysis}}
        
        ## 版本计算
        
        {{version_calc}}
        
        ## Release Notes
        
        {{release_notes}}
        
        ## 发布检查清单
        
        - [ ] 所有测试通过
        - [ ] 文档已更新
        - [ ] CHANGELOG已更新
        - [ ] 版本号已更新
        
        ---
        *由 Trae 自动生成*

  - id: 6
    name: 验证报告生成
    action: verify
    type: file_exists
    path: "output/release-report-{{current_date}}.md"
    fail_message: "发布报告未生成"

  - id: 7
    name: 输出发布结果
    action: notify
    params:
      message: |
        ✅ 智能发布分析完成！
        
        变更分析:
        {{change_analysis}}
        
        版本建议:
        {{version_calc}}
        
        Release Notes:
        {{release_notes}}
        
        报告: output/release-report-{{current_date}}.md