name: 工作流系统优化
description: 分析工作流使用情况，优化执行效率
version: "1.0.0"
created_at: "2026-02-11T12:00:00"
triggers:
  - "优化工作流"
  - "workflow optimization"
  - "系统优化"
steps:
  - id: 1
    name: 分析工作流使用统计
    action: run_command
    params:
      command: |
        echo "=== 工作流使用统计 ===" &&
        echo "" &&
        echo "扫描工作流目录..." &&
        dir /b .trae\workflows\*.yaml 2>nul | find /c ".yaml" || echo "0"
      save_as: workflow_stats
      timeout: 10

  - id: 2
    name: 生成优化建议
    action: generate_document
    params:
      template: "workflow-optimization.md"
      variables:
        stats: "{{workflow_stats}}"
        date: "{{current_date}}"
      output: "docs/workflow-optimization-{{current_date}}.md"
      save_as: report_path

  - id: 3
    name: 完成通知
    action: notify
    params:
      message: |
        工作流系统优化分析完成！
        统计: {{workflow_stats}}
        报告: {{report_path}}